// This file has been autogenerated from a class added in the UI designer.

using System;

using CoreGraphics;

using Foundation;
using UIKit;

namespace BoaBee.iOS
{
	public partial class HighlightableButton : UIButton
	{
		private bool isSubscribedForAppDelegateCallback = false;

		public HighlightableButton (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			if (!this.isSubscribedForAppDelegateCallback) 
			{
				this.isSubscribedForAppDelegateCallback = true;

				NSNotificationCenter.DefaultCenter.AddObserver (this, new ObjCRuntime.Selector ("callbackHandler:"), new NSString("HighlightableButton_AppResignActive"), UIApplication.SharedApplication.WeakDelegate);
			}
		}

		[Export("callbackHandler:")]
		private void callbackHandler(NSNotification notification)
		{
			this.Highlighted = false;
		}

		public override bool PointInside (CGPoint point, UIEvent uievent)
		{
			bool inside = base.PointInside (point, uievent);

//            if (inside && uievent.Type == UIEventType.Touches)
			if (inside && !this.Highlighted && uievent.Type == UIEventType.Touches)
			{
				this.Highlighted = true;
			}
			else
			{
				this.Highlighted = false;
			}
			return inside;
		}

		public override bool BeginTracking(UITouch uitouch, UIEvent uievent)
		{
			this.Highlighted = true;
			return base.BeginTracking(uitouch, uievent);
		}

		public override void EndTracking(UITouch uitouch, UIEvent uievent)
		{
			base.EndTracking(uitouch, uievent);
			this.Highlighted = false;
		}
	}
}
