// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class AnswerCell : UITableViewCell
	{
		public AnswerCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithOption(string option)
        {
            this.optionLabel.Text = option;
        }

		public void initWithOption(string option, int size, DBColor textColor, DBColor backgroundColor)
		{
			this.optionLabel.Text = option;
			this.optionLabel.TextColor = UIColor.FromRGB(textColor.red, textColor.green, textColor.blue);

			this.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);
			this.ContentView.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);

			this.optionLabel.Font = this.optionLabel.Font.WithSize(size);
		}
	}
}
