// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class AnswerTypingCell : UITableViewCell
	{
		public AnswerTypingCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithAnswerAndTag(string answer, int tag)
        {
            this.inputTextView.Tag = tag;
            this.inputTextView.Text = answer;

			//this.inputTextField.Tag = tag;
			//this.inputTextField.Text = answer;
        }

		public void initWithAnswerAndTag(string answer, int tag, int size, DBColor textColor, DBColor backgroundColor)
		{
			this.inputTextView.Font = this.inputTextView.Font.WithSize(size);
			//this.inputTextField.Font = this.inputTextField.Font.WithSize(size);

			this.inputTextView.Tag = tag;
			this.inputTextView.Text = answer;
			this.inputTextView.TextColor = UIColor.FromRGB(textColor.red, textColor.green, textColor.blue);

			//this.inputTextField.Tag = tag;
			//this.inputTextField.Text = answer;
			//this.inputTextField.TextColor = UIColor.FromRGB(textColor.red, textColor.green, textColor.blue);

			this.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);
			this.ContentView.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);
		}

		public UITextView getTextView()
		{
			return this.inputTextView;
		}

		//public UITextField getTextField()
		//{
		//	return this.inputTextField;
		//}
	}
}
