// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BoaBee.iOS
{
	public partial class AppCell : UITableViewCell
	{
		//Filled from table source
		public string appName { private get; set; }
		//--

		public AppCell (IntPtr handle) : base (handle)
		{
		}

		#warning move it to superclass
		//public override void AwakeFromNib ()
		//{
		//	base.AwakeFromNib ();

		//	var a = this.BackgroundColor;

		//	this.BackgroundColor = a;
		//}

		public void initCell()
		{
			profileNameLabel.Text = appName.ToUpper ();
		}
	}
}
