// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BoaBee.iOS
{
	public partial class BackCell : UITableViewCell
	{
		public BackCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithParentName(string name)
        {
            this.parentFolderNameLabel.Text = name;
        }
	}
}
