// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class ContactEmailCell : UITableViewCell
	{
		public ContactEmailCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithContact(DBlocalContact contact, DateTime date)
		{
			if (!string.IsNullOrEmpty(contact.firstname) || !string.IsNullOrEmpty(contact.lastname))
            {
                if (!string.IsNullOrEmpty(contact.company))
                {
                    this.contactNameLabel.Text = string.Format("{0} {1} ({2})", contact.firstname, contact.lastname, contact.company);
                }
                else
                {
                    this.contactNameLabel.Text = string.Format("{0} {1}", contact.firstname, contact.lastname);
                }
            }
            else
            {
                this.contactNameLabel.Text = contact.uid;
            }

			this.dateLabel.Text = string.Format ("{0:yyyy-MM-dd}", date);
			this.timeLabel.Text = string.Format ("{0:H:mm:ss}", date);
		}
	}
}
