// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BoaBee.iOS
{
	public partial class FileDetailCell : UITableViewCell
	{
		public FileDetailCell (IntPtr handle) : base (handle)
		{
		}

		public void initWithFile(string filename)
		{
			this.fileNameLabel.Text = filename;
		}
	}
}
