// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class FilesOverviewCell : UITableViewCell
	{
		public FilesOverviewCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithFile(DBfileTO file)
		{
			this.fileNameLabel.Text = file.name;
		}
	}
}
