// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class FileCell : UITableViewCell
	{
		public FileCell (IntPtr handle) : base (handle)
		{
		}

		public void initWithFile(DBfileTO file, bool isAdded)
        {
			switch (file.fileType)
			{
				case "url":
				{
					this.fileTypeLabel.Text = "www";
					break;
				}
				case "webloc":
				{
					this.fileTypeLabel.Text = "www";
					break;
				}
				default:
				{
					this.fileTypeLabel.Text = file.fileType;
					break;
				}
			}

			this.checkboxButton.SetImage(UIImage.FromBundle("CheckboxUnchecked"), UIControlState.Normal);
			this.checkboxButton.SetImage(UIImage.FromBundle("CheckboxChecked"), UIControlState.Selected);
			this.checkboxButton.Selected = isAdded;

            this.fileNameLabel.Text = file.name;
        }
	}
}
