// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class QuestionCell : UITableViewCell
	{
		public QuestionCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithQuestion(DBQuestion question)
        {
            this.questionLabel.Text = question.question;

            #if DEBUG
            {
                if (question.required)
                {
                    this.questionLabel.Text += " (*)";
                }
                else
                {
                    this.questionLabel.Text += " (#)";
                }
            }
            #endif
        }

		public void initWithQuestion(DBQuestion question, int size, DBColor textColor, DBColor backgroundColor)
		{
			this.questionLabel.Text = question.question;
			this.questionLabel.TextColor = UIColor.FromRGB(textColor.red, textColor.green, textColor.blue);

			this.questionLabel.Font = this.questionLabel.Font.WithSize(size);

			this.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);
			this.ContentView.BackgroundColor = UIColor.FromRGB(backgroundColor.red, backgroundColor.green, backgroundColor.blue);
		}
	}
}
