// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class SelectQuestionsCell : UITableViewCell
	{
		public SelectQuestionsCell (IntPtr handle) : base (handle)
		{
		}

        public void initWithFormDefinition(DBFormDefinition formDefinition)
        {
            this.questionnaireNameLabel.Text = formDefinition.objectName;
        }
	}
}
