// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;
using System.Threading.Tasks;

namespace BoaBee.iOS
{
	public partial class AppSettingsViewController : UIViewController
	{
		public AppSettingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DBAppSettings appSettings = DBLocalDataStore.GetInstance().GetAppSettings();
            if (appSettings != null)
            {
                this.contactCheckSwitch.On = appSettings.instantContactCheck;
            }
        }

        partial void closeButtonClick(UIButton sender)
        {
            bool instantContactCheck = this.contactCheckSwitch.On;
            Task.Run(() =>
            {
                DBAppSettings appSettings = new DBAppSettings();
                appSettings.instantContactCheck = instantContactCheck;
                DBLocalDataStore.GetInstance().SetAppSettings(appSettings);
            });

            this.NavigationController.PopViewController(true);
        }
	}
}
