// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class BoabeeProspectNavController : UINavigationController
	{
		public BoabeeProspectNavController (IntPtr handle) : base (handle)
		{
		}

        public override void DismissViewController(bool animated, Action completionHandler)
        {
            Console.Error.WriteLine("Prospect dismissimg!");

            NSUserDefaults.StandardUserDefaults.RemoveObject("ProspectLastScreen");
            NSUserDefaults.StandardUserDefaults.Synchronize();

            base.DismissViewController(animated, completionHandler);
        }
	}
}
