// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BoaBee.iOS
{
	public partial class BoabeeRootNavController : UINavigationController
	{
		public BoabeeRootNavController (IntPtr handle) : base (handle)
		{
		}
	}
}
