// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class ContactOverviewRootViewController : UIViewController
	{
		public int contactID;

		private ContactOverviewTableViewController contactTableViewController;

		public ContactOverviewRootViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

            var customer = DBLocalDataStore.GetInstance().GetLocalContactsById(contactID);

			this.contactTableViewController = (ContactOverviewTableViewController)this.ChildViewControllers[0];
			this.contactTableViewController.initTableViewWithContact(customer);

            //#warning get contact source
            switch (customer.source)
            {
                case ContactSource.Edit:
                {
                    this.statusLabel.Text = "edited, only stored locally";
                    break;
                }
                case ContactSource.Manual:
                {
                    this.statusLabel.Text = "manually added, only stored locally";
                    break;
                }
                case ContactSource.Scanned:
                {
                    this.statusLabel.Text = "scanned, only stored locally";
                    break;
                }
                case ContactSource.Server:
                {
                    this.statusLabel.Text = "safely stored in the cloud";
                    break;
                }
            }
		}

		partial void closeButtonClick (UIButton sender)
		{
			this.NavigationController.PopViewController(true);
		}
	}
}
