// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class ContactOverviewTableViewController : UITableViewController
	{
		public ContactOverviewTableViewController (IntPtr handle) : base (handle)
		{
		}

        public void initTableViewWithContact(DBlocalContact contact)
		{
			this.firstNameLabel.Text = contact.firstname;
			this.lastNameLabel.Text = contact.lastname;
			this.emailLabel.Text = contact.email;
			this.companyLabel.Text = contact.company;
			this.phoneLabel.Text = contact.phone;
            this.idLabel.Text = contact.uid;
			this.jobTitleLabel.Text = contact.jobtitle;
			this.countryLabel.Text = contact.country;
			this.cityLabel.Text = contact.city;
			this.streetLabel.Text = contact.street;
			this.zipLabel.Text = contact.zip;
		}
	}
}
