// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace BoaBee.iOS
{
	public partial class EditAnswerViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate
	{
		public InfoSheetViewController caller;

		public NSDictionary questionDictionary;
		private List<string> optionsArray = new List<string>();
		private NSNumber questionNumber;

		public EditAnswerViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			string options = this.questionDictionary["options"].ToString();
			this.questionNumber = (NSNumber)this.questionDictionary["questionNumber"];

			this.optionsArray = new List<string>(options.Split(new string[] {"_,_"}, StringSplitOptions.RemoveEmptyEntries));
			this.questionLabel.Text = this.questionDictionary["question"].ToString();

			this.answersTableView.EstimatedRowHeight = 44;
			this.answersTableView.RowHeight = UITableView.AutomaticDimension;
		}

		public nint RowsInSection(UITableView tableView, nint section)
		{
			return this.optionsArray.Count;
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			AnswerCell cell = (AnswerCell)tableView.DequeueReusableCell("cell", indexPath);

			cell.initWithOption(this.optionsArray[indexPath.Row]);

			return cell;
		}

		[Export("tableView:didSelectRowAtIndexPath:")]
		public void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow(indexPath, true);

			NSDictionary userInfo = NSDictionary.FromObjectsAndKeys(new NSObject[] {(NSString)this.optionsArray[indexPath.Row], this.questionNumber }, new NSObject[] {(NSString)"selectedOption", (NSString)"questionNumber"});

			this.caller.didSelectAnswer(userInfo);
			this.NavigationController.PopViewController(true);
		}

		partial void cancelButtonClick (UIKit.UIButton sender)
		{
			this.NavigationController.PopViewController(true);
		}
	}
}
