// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using BoaBeePCL;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace BoaBee.iOS
{
	public partial class EditContactTableViewController : UITableViewController
	{
		public EditContactTableViewController (IntPtr handle) : base (handle)
		{
		}

        private string uid;
        private int oldDatabaseID;

        public DBlocalContact getContact()
        {
            DBlocalContact newContact = new DBlocalContact();

            newContact.firstname = this.firstNameTextField.Text.Length > 0 ? this.firstNameTextField.Text : null;
            newContact.lastname = this.lastNameTextField.Text.Length > 0 ? this.lastNameTextField.Text : null;
            newContact.email = this.emailTextField.Text.Length > 0 ? this.emailTextField.Text : null;
            newContact.company = this.companyTextField.Text.Length > 0 ? this.companyTextField.Text : null;
            newContact.phone = phoneTextField.Text.Length > 0 ? this.phoneTextField.Text : null;
            newContact.jobtitle = this.jobTitleTextField.Text.Length > 0 ? this.jobTitleTextField.Text : null;
            newContact.street = this.streetTextField.Text.Length > 0 ? this.streetTextField.Text : null;
            newContact.city = this.cityTextField.Text.Length > 0 ? this.cityTextField.Text : null;
            newContact.country = this.countryTextField.Text.Length > 0 ? this.countryTextField.Text : null;
            newContact.zip = this.zipTextField.Text.Length > 0 ? this.zipTextField.Text : null;

            newContact.uid = this.uid;
            newContact.Id = this.oldDatabaseID;

            return newContact;
        }

        public void setContact(DBlocalContact contact)
        {
            Console.Error.WriteLine("editing contact: \n{0}", JsonConvert.SerializeObject(contact).Replace(",", "\r\n"));

            this.uid = contact.uid;
            this.oldDatabaseID = contact.Id;

            this.firstNameTextField.Text = contact.firstname;
            this.lastNameTextField.Text = contact.lastname;
            this.emailTextField.Text = contact.email;
            this.companyTextField.Text = contact.company;
            this.phoneTextField.Text = contact.phone;
            this.jobTitleTextField.Text = contact.jobtitle;
            this.cityTextField.Text = contact.city;
            this.streetTextField.Text = contact.street;
            this.countryTextField.Text = contact.country;
            this.zipTextField.Text = contact.zip;

            this.idTextField.Text = contact.uid;

            this.idTextField.Enabled = false;
        }
	}
}
