// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class EmailSentViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate
	{
        public DBOrder order;
        public bool isSent;

		//private List<DBOverviewFileTO> files = new List<DBOverviewFileTO>();

		public EmailSentViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			this.filesTableView.EstimatedRowHeight = 44;
			this.filesTableView.RowHeight = UITableView.AutomaticDimension;

            var customer = DBLocalDataStore.GetInstance().GetLocalContactsByUID(order.contactUid);

			if (!string.IsNullOrEmpty(customer.firstname) || !string.IsNullOrEmpty(customer.lastname))
			{
                this.contactNameLabel.Text = string.Format(string.IsNullOrEmpty(customer.company)? "{0} {1}":"{0} {1} ({2})", customer.firstname, customer.lastname, customer.company);
			} 
			else 
			{
                this.contactNameLabel.Text = string.Format("{0}", customer.uid);
			}

            DateTime date = DateTime.Parse(order.created);

			this.dateTimeLabel.Text = string.Format("{0:dd/MMM/yyyy H:mm:ss}", new DateTimeOffset(date));

            this.statusLabel.Text = !this.isSent ? "only stored locally" : "safely stored in the cloud";
		}

		partial void closeButtonClick (UIButton sender)
		{
			this.NavigationController.PopViewController(true);
		}

		public nint RowsInSection(UITableView tableView, nint section)
		{
            return this.order.orderLine.Count;
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
            DBOrderLine fileForCell = this.order.orderLine[indexPath.Row];
			
			FileDetailCell cell = (FileDetailCell)tableView.DequeueReusableCell("fileCell", indexPath);
            cell.initWithFile(fileForCell.itemDescription);

			return cell;
		}
	}
}
