// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;
using BoaBeePCL;
using System.Linq;
using CoreGraphics;
using Newtonsoft.Json;
using BoaBeeLogic;

namespace BoaBee.iOS
{
	public partial class EmailsSentViewController : UIViewController, IUITableViewDelegate, IUITableViewDataSource
	{
		public EmailsSentViewController (IntPtr handle) : base (handle)
		{
		}

        private List<DBSyncRequest> syncRequests;
        private List<DBlocalContact> contactsMet;

		//private List<DBOverviewContacts> needContactsShow = new List<DBOverviewContacts>();
		//private List<DBOverviewContacts> filteredContacts = new List<DBOverviewContacts>();
		//private List<DBOverviewContacts> barcodeContacts = new List<DBOverviewContacts>();
		//private List<DBOverviewContacts> nameContacts = new List<DBOverviewContacts>();

		private NSObject kbFrameChangeNoificationToken;

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

            this.contactsMet = new List<DBlocalContact>();
            this.syncRequests = DBLocalDataStore.GetInstance().getSyncRequests().ToList();

            syncRequests.ForEach((r) =>
            {
                SyncContext context = JsonConvert.DeserializeObject<SyncContext>(r.serializedSyncContext);
                if (!context.orders.isNullOrEmpty())
                {
                    context.orders.ForEach((f) =>
                    {
                        var contact = DBLocalDataStore.GetInstance().GetLocalContactsByUID(f.contactUid);
                        this.contactsMet.Add(contact);
                    });
                }
            });

            emailsSentLabel.Text = this.contactsMet.Count.ToString() + " EMAILS SENT";

			this.contactsTableView.EstimatedRowHeight = 44;
			this.contactsTableView.RowHeight = UITableView.AutomaticDimension;

			UIStringAttributes placeholderAttributes = new UIStringAttributes();
			placeholderAttributes.ForegroundColor = UIColor.FromRGB(0x71, 0x71, 0x71);

			NSAttributedString searchPlaceholder = new NSAttributedString (this.searchTextField.Placeholder, placeholderAttributes);

			this.searchTextField.AttributedPlaceholder = searchPlaceholder;
		}
			
		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);

			this.kbFrameChangeNoificationToken = UIKeyboard.Notifications.ObserveWillChangeFrame(kbFrameChangeCallback);
		}

		public override void ViewWillDisappear(bool animated)
		{
			base.ViewWillDisappear(animated);

			if (this.kbFrameChangeNoificationToken != null)
			{
				this.kbFrameChangeNoificationToken.Dispose();
				this.kbFrameChangeNoificationToken = null;
			}
		}

		private void kbFrameChangeCallback (object sender, UIKeyboardEventArgs args)
		{
			CGRect beginFrame = args.FrameBegin;
			CGRect endFrame = args.FrameEnd;

			UIView.Animate(args.AnimationDuration, 
				() =>
				{
					this.bottomButtonsConstraint.Constant += (beginFrame.Y - endFrame.Y);
					this.View.LayoutIfNeeded();
				});
		}

		partial void searchTextFieldEditingChanged (UITextField sender)
		{
			//List<DBOverviewContacts> matchedContacts = (this.nameContacts.Where(s => string.Join(" ", new string[] {s.firstName, s.lastName, s.company}).ToLower().Contains(sender.Text.ToLower())).Concat
			//	(this.barcodeContacts.Where(s => string.Format("badge {0}", s.barcode.ToLower()).Contains(sender.Text.ToLower())))).ToList();

			//this.filteredContacts.Clear();
			//this.filteredContacts.AddRange(matchedContacts);

			this.contactsTableView.ReloadData();
		}

		partial void searchTextFieldEditingDidBegin (UITextField sender)
		{

		}

		partial void searchTextFieldEditingDidEnd (UITextField sender)
		{

		}

		partial void cancelButtonClick (UIButton sender)
		{
			this.NavigationController.PopViewController(true);
		}

        [Export("numberOfSectionsInTableView:")]
        public nint NumberOfSections(UITableView tableView)
        {
            return this.syncRequests.Count;
        }

		public nint RowsInSection(UITableView tableView, nint section)
		{
			var request = this.syncRequests[(int)section];
            SyncContext context = JsonConvert.DeserializeObject<SyncContext>(request.serializedSyncContext);

            if (this.searchTextField.Text.Length > 0)
            {
                var count = 0;
                if (!context.orders.isNullOrEmpty())
                {
                    var listMatched = context.orders.Where(f => this.contactsMet.Where(s => string.Join(" ", new string[] { s.firstname, s.lastname, s.company }).ToLower().Contains(this.searchTextField.Text.ToLower())).ToList().Find(c => c.uid.Equals(f.contactUid)) != null).ToList();
                    listMatched = listMatched.Where(o => o.orderLine.Count > 0).ToList();
                    count = listMatched.Count;
                }
                return count;
            }

            return context.orders.isNullOrEmpty() ? 0 : context.orders.Where(o => o.orderLine.Count > 0).Count();
            //return context.orders.Where(o => o.orderLine.Count > 0).Count();
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			ContactEmailCell cell = (ContactEmailCell)tableView.DequeueReusableCell("ContactCell", indexPath);

            var request = this.syncRequests[indexPath.Section];
            SyncContext context = JsonConvert.DeserializeObject<SyncContext>(request.serializedSyncContext);

            DBlocalContact contact = null;
            if (this.searchTextField.Text.Length > 0)
            {
                contact = DBLocalDataStore.GetInstance().GetLocalContactsByUID(context.orders.Where(f => this.contactsMet.Where(s => string.Join(" ", new string[] { s.firstname, s.lastname, s.company }).ToLower().Contains(this.searchTextField.Text.ToLower())).ToList().Find(c => c.uid.Equals(f.contactUid)) != null).ToList()[indexPath.Row].contactUid);
            }
            else
            {
                contact = DBLocalDataStore.GetInstance().GetLocalContactsByUID(context.orders.Where(o => o.orderLine.Count > 0).ToList()[indexPath.Row].contactUid);
            }

            cell.initWithContact(contact, DateTime.Parse(context.orders[indexPath.Row].created));
			return cell;
		}

		[Export("tableView:didSelectRowAtIndexPath:")]
		public void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow(indexPath, true);

            var request = this.syncRequests[indexPath.Section];
            SyncContext context = JsonConvert.DeserializeObject<SyncContext>(request.serializedSyncContext);

            DBlocalContact contact = null;
            DBOrder order = null;

            if (this.searchTextField.Text.Length > 0)
            {
                order = context.orders.Where(f => this.contactsMet.Where(s => string.Join(" ", new string[] { s.firstname, s.lastname, s.company }).ToLower().Contains(this.searchTextField.Text.ToLower())).ToList().Find(c => c.uid.Equals(f.contactUid)) != null).ToList()[indexPath.Row];
            }
            else
            {
                order = context.orders.Where(o => o.orderLine.Count > 0).ToList()[indexPath.Row];
            }

            contact = DBLocalDataStore.GetInstance().GetLocalContactsByUID(order.contactUid);
            Console.Error.WriteLine(string.Join(" ", contact.firstname, contact.lastname));
            NSMutableDictionary dict = new NSMutableDictionary();
            dict.Add((NSString)"order", (NSString)JsonConvert.SerializeObject(order));
            dict.Add((NSString)"isSent", NSNumber.FromBoolean(request.isSent));

            this.PerformSegue("toEmailSentDetails", dict);
		}

		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
            if (segue.Identifier.Equals("toEmailSentDetails"))
            {
                EmailSentViewController target = (EmailSentViewController)segue.DestinationViewController;

                NSDictionary dict = (NSDictionary)sender;

                DBOrder order = JsonConvert.DeserializeObject<DBOrder>(dict["order"].ToString());
                bool isSent = ((NSNumber)dict["isSent"]).BoolValue;

                target.isSent = isSent;
                target.order = order;
			}
		}

	}
}
