// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using CoreGraphics;

using Foundation;
using UIKit;

using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class FilesOverviewViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate
	{
        public List<DBfileTO> addedFiles = new List<DBfileTO>();

		public FilesOverviewViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			//this.addedFiles = DBLocalDataStore.GetInstance().GetLocalFilesPopup();

			this.filesTableView.EstimatedRowHeight = 44;
			this.filesTableView.RowHeight = UITableView.AutomaticDimension;
		}

		public nint RowsInSection(UITableView tableView, nint section)
		{
			return this.addedFiles.Count;
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
            DBfileTO file = this.addedFiles[indexPath.Row];

			FilesOverviewCell cell = (FilesOverviewCell)tableView.DequeueReusableCell("FileCell", indexPath);

			cell.initWithFile(file);
			return cell;
		}

		partial void cancelButtonClick (UIButton sender)
		{
			this.NavigationController.PopViewController(true);
		}

		partial void deleteButtonClick (UIButton sender, UIEvent @event)
		{
			UITouch touch = (UITouch)@event.TouchesForView(sender).AnyObject;
			CGPoint touchLocation = touch.LocationInView(this.filesTableView);

			NSIndexPath indexPath = this.filesTableView.IndexPathForRowAtPoint(touchLocation);

            DBfileTO file = this.addedFiles[indexPath.Row];
            file.activeFile = false;
            DBLocalDataStore.GetInstance().UpdateLocalFile(file);

			this.addedFiles.RemoveAt(indexPath.Row);
			this.filesTableView.BeginUpdates();

			this.filesTableView.DeleteRows(new NSIndexPath[]{indexPath}, UITableViewRowAnimation.Automatic);

			this.filesTableView.EndUpdates();

			if (this.addedFiles.Count == 0)
			{
				this.NavigationController.PopViewController(true);
			}
		}
	}
}
