// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;
using BoaBeePCL;

namespace BoaBee.iOS
{
	public partial class NewContactTableViewController : UITableViewController
	{
		public NewContactTableViewController (IntPtr handle) : base (handle)
		{
		}

		public Dictionary<string, string> getNewContactDict()
		{
			Dictionary<string, string> newContactDict = new Dictionary<string, string>();

            newContactDict.Add("firstName", this.firstNameTextField.Text.Length > 0 ? this.firstNameTextField.Text : null);
            newContactDict.Add("lastName", this.lastNameTextField.Text.Length > 0 ? this.lastNameTextField.Text : null);
            newContactDict.Add("email", this.emailTextField.Text.Length > 0 ? this.emailTextField.Text : null);
            newContactDict.Add("company", this.companyTextField.Text.Length > 0 ? this.companyTextField.Text : null);
            newContactDict.Add("phone", this.phoneTextField.Text.Length > 0 ? this.phoneTextField.Text : null);
            newContactDict.Add("jobTitle", this.jobTitleTextField.Text.Length > 0 ? this.jobTitleTextField.Text : null);
            newContactDict.Add("street", this.streetTextField.Text.Length > 0 ? this.streetTextField.Text : null);
            newContactDict.Add("city", this.cityTextField.Text.Length > 0 ? this.cityTextField.Text : null);
            newContactDict.Add("country", this.countryTextField.Text.Length > 0 ? this.countryTextField.Text : null);
            newContactDict.Add("zip", this.zipTextField.Text.Length > 0 ? this.zipTextField.Text : null);

			return newContactDict;
		}

        public DBlocalContact getNewContact()
        {
            DBlocalContact newContact = new DBlocalContact();

            newContact.firstname = this.firstNameTextField.Text.Length > 0 ? this.firstNameTextField.Text : null;
            newContact.lastname = this.lastNameTextField.Text.Length > 0 ? this.lastNameTextField.Text : null;
            newContact.email = this.emailTextField.Text.Length > 0 ? this.emailTextField.Text : null;
            newContact.company = this.companyTextField.Text.Length > 0 ? this.companyTextField.Text : null;
            newContact.phone = phoneTextField.Text.Length > 0 ? this.phoneTextField.Text : null;
            newContact.jobtitle = this.jobTitleTextField.Text.Length > 0 ? this.jobTitleTextField.Text : null;
            newContact.street = this.streetTextField.Text.Length > 0 ? this.streetTextField.Text : null;
            newContact.city = this.cityTextField.Text.Length > 0 ? this.cityTextField.Text : null;
            newContact.country = this.countryTextField.Text.Length > 0 ? this.countryTextField.Text : null;
            newContact.zip = this.zipTextField.Text.Length > 0 ? this.zipTextField.Text : null;

            newContact.uid = newContact.email;

            return newContact;
        }
	}
}
